#
# Copyright (c) nexB Inc. and others.
# SPDX-License-Identifier: Apache-2.0
#
# Visit https://aboutcode.org and https://github.com/aboutcode-org/univers for support and download.

import json
from pathlib import Path

import pytest

from univers.version_range import NixVersionRange
from univers.versions import InvalidVersion
from univers.versions import NixVersion

from . import SchemaDrivenVersTest

TEST_DATA = Path(__file__).parent / "data" / "schema" / "nix_version_cmp.json"


class NixVersionComparison(SchemaDrivenVersTest):
    def equality(self):
        """Compare version1 and version2 are equal."""
        return NixVersion(self.input_version1) == NixVersion(self.input_version2)

    def comparison(self):
        """Sort version1 and version2 and return them in the correct order."""
        sorts = sorted(
            [
                NixVersion(self.input_version1),
                NixVersion(self.input_version2),
            ]
        )
        return [sorts[0].string, sorts[1].string]


@pytest.mark.parametrize("test_case", json.load(open(TEST_DATA)))
def test_nix_vers_cmp(test_case):
    """
    The test data is generated by evaluating builtins.compareVersions with
    nix-instantiate over all pairs from a corpus of version strings, so these
    cases are the reference implementation's own answers.
    Regenerate with etc/scripts/gen_nix_version_cmp.py.
    """
    nvc = NixVersionComparison.from_data(data=test_case)
    nvc.assert_result()


@pytest.mark.parametrize(
    ("older", "newer"),
    [
        # Numeric components compare as integers, not strings.
        ("1.9", "1.10"),
        # The component "pre" sorts before everything, so 2.3pre1 is a
        # pre-release of 2.3. No other pre-release marker is special:
        # 2.3a extends the version instead and sorts after 2.3.
        ("2.3pre1", "2.3"),
        ("2.3", "2.3a"),
        ("2.3a", "2.3.1"),
        # A leading "v" is an ordinary component, not decoration.
        ("v1.0", "1.0"),
        # Digit runs overflowing a C integer compare as strings, which sort
        # before any numeric component.
        ("2147483648", "2147483647"),
    ],
)
def test_nix_version_ordering_quirks(older, newer):
    assert NixVersion(older) < NixVersion(newer)


def test_nix_version_equivalent_separators():
    assert NixVersion("1.0") == NixVersion("1-0")
    assert NixVersion("2.3pre1") == NixVersion("2.3-pre.1")
    assert NixVersion("1.007") == NixVersion("1.7")


def test_nix_version_rejects_empty():
    with pytest.raises(InvalidVersion):
        NixVersion("")


def test_nix_version_range():
    version_range = NixVersionRange.from_string("vers:nix/>=1.2.3|<2.0")
    assert NixVersion("1.9") in version_range
    assert NixVersion("1.10") in version_range
    assert NixVersion("2.0pre1") in version_range
    assert NixVersion("2.0") not in version_range
    assert NixVersion("1.2.3pre1") not in version_range
    assert str(version_range) == "vers:nix/>=1.2.3|<2.0"
